"""autogenerated by genpy from state_manager_communications/robotModeMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class robotModeMsg(genpy.Message):
  _md5sum = "f72c1608aab809dbbc4df281d3ec0dfa"
  _type = "state_manager_communications/robotModeMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string nodeName

uint8 mode
uint8 MODE_OFF = 0
uint8 MODE_NORMAL = 1


uint8 type
uint8 TYPE_TRANSITION = 0
uint8 TYPE_START = 1
uint8 TYPE_REQUEST = 3
uint8 TYPE_ACK = 4

"""
  # Pseudo-constants
  MODE_OFF = 0
  MODE_NORMAL = 1
  TYPE_TRANSITION = 0
  TYPE_START = 1
  TYPE_REQUEST = 3
  TYPE_ACK = 4

  __slots__ = ['nodeName','mode','type']
  _slot_types = ['string','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       nodeName,mode,type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(robotModeMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.nodeName is None:
        self.nodeName = ''
      if self.mode is None:
        self.mode = 0
      if self.type is None:
        self.type = 0
    else:
      self.nodeName = ''
      self.mode = 0
      self.type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.nodeName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2B.pack(_x.mode, _x.type))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.nodeName = str[start:end].decode('utf-8')
      else:
        self.nodeName = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.mode, _x.type,) = _struct_2B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.nodeName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2B.pack(_x.mode, _x.type))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.nodeName = str[start:end].decode('utf-8')
      else:
        self.nodeName = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.mode, _x.type,) = _struct_2B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B = struct.Struct("<2B")
