/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mike/svn/nasia/trunk/philosophers/src/remote_mutex/srv/mutexSrv.srv
 *
 */


#ifndef REMOTE_MUTEX_MESSAGE_MUTEXSRVRESPONSE_H
#define REMOTE_MUTEX_MESSAGE_MUTEXSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace remote_mutex
{
template <class ContainerAllocator>
struct mutexSrvResponse_
{
  typedef mutexSrvResponse_<ContainerAllocator> Type;

  mutexSrvResponse_()
    : status(0)  {
    }
  mutexSrvResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
    }



   typedef uint8_t _status_type;
  _status_type status;


    enum { STATUS_LOCKED = 1 };
     enum { STATUS_UNLOCKED = 0 };
 

  typedef boost::shared_ptr< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct mutexSrvResponse_

typedef ::remote_mutex::mutexSrvResponse_<std::allocator<void> > mutexSrvResponse;

typedef boost::shared_ptr< ::remote_mutex::mutexSrvResponse > mutexSrvResponsePtr;
typedef boost::shared_ptr< ::remote_mutex::mutexSrvResponse const> mutexSrvResponseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::remote_mutex::mutexSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace remote_mutex

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d5878401ab4f108105f53837a17fdb3";
  }

  static const char* value(const ::remote_mutex::mutexSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d5878401ab4f108ULL;
  static const uint64_t static_value2 = 0x105f53837a17fdb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "remote_mutex/mutexSrvResponse";
  }

  static const char* value(const ::remote_mutex::mutexSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n\
uint8 STATUS_LOCKED = 1\n\
uint8 STATUS_UNLOCKED = 0\n\
\n\
\n\
";
  }

  static const char* value(const ::remote_mutex::mutexSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct mutexSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::remote_mutex::mutexSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::remote_mutex::mutexSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REMOTE_MUTEX_MESSAGE_MUTEXSRVRESPONSE_H
