/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mike/philosophers_experiments/philosophers/src/remote_mutex/srv/mutexSrv.srv
 *
 */


#ifndef REMOTE_MUTEX_MESSAGE_MUTEXSRV_H
#define REMOTE_MUTEX_MESSAGE_MUTEXSRV_H

#include <ros/service_traits.h>


#include <remote_mutex/mutexSrvRequest.h>
#include <remote_mutex/mutexSrvResponse.h>


namespace remote_mutex
{

struct mutexSrv
{

typedef mutexSrvRequest Request;
typedef mutexSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mutexSrv
} // namespace remote_mutex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::remote_mutex::mutexSrv > {
  static const char* value()
  {
    return "76380b12c62c62b1c75ef04892016d2b";
  }

  static const char* value(const ::remote_mutex::mutexSrv&) { return value(); }
};

template<>
struct DataType< ::remote_mutex::mutexSrv > {
  static const char* value()
  {
    return "remote_mutex/mutexSrv";
  }

  static const char* value(const ::remote_mutex::mutexSrv&) { return value(); }
};


// service_traits::MD5Sum< ::remote_mutex::mutexSrvRequest> should match 
// service_traits::MD5Sum< ::remote_mutex::mutexSrv > 
template<>
struct MD5Sum< ::remote_mutex::mutexSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::remote_mutex::mutexSrv >::value();
  }
  static const char* value(const ::remote_mutex::mutexSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_mutex::mutexSrvRequest> should match 
// service_traits::DataType< ::remote_mutex::mutexSrv > 
template<>
struct DataType< ::remote_mutex::mutexSrvRequest>
{
  static const char* value()
  {
    return DataType< ::remote_mutex::mutexSrv >::value();
  }
  static const char* value(const ::remote_mutex::mutexSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::remote_mutex::mutexSrvResponse> should match 
// service_traits::MD5Sum< ::remote_mutex::mutexSrv > 
template<>
struct MD5Sum< ::remote_mutex::mutexSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::remote_mutex::mutexSrv >::value();
  }
  static const char* value(const ::remote_mutex::mutexSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_mutex::mutexSrvResponse> should match 
// service_traits::DataType< ::remote_mutex::mutexSrv > 
template<>
struct DataType< ::remote_mutex::mutexSrvResponse>
{
  static const char* value()
  {
    return DataType< ::remote_mutex::mutexSrv >::value();
  }
  static const char* value(const ::remote_mutex::mutexSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REMOTE_MUTEX_MESSAGE_MUTEXSRV_H
