/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mike/svn/nasia/trunk/philosophers/src/state_manager_communications/srv/registerNodeSrv.srv
 *
 */


#ifndef STATE_MANAGER_COMMUNICATIONS_MESSAGE_REGISTERNODESRV_H
#define STATE_MANAGER_COMMUNICATIONS_MESSAGE_REGISTERNODESRV_H

#include <ros/service_traits.h>


#include <state_manager_communications/registerNodeSrvRequest.h>
#include <state_manager_communications/registerNodeSrvResponse.h>


namespace state_manager_communications
{

struct registerNodeSrv
{

typedef registerNodeSrvRequest Request;
typedef registerNodeSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct registerNodeSrv
} // namespace state_manager_communications


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_manager_communications::registerNodeSrv > {
  static const char* value()
  {
    return "fa90f177c62ffd4f5a57999c98f4104f";
  }

  static const char* value(const ::state_manager_communications::registerNodeSrv&) { return value(); }
};

template<>
struct DataType< ::state_manager_communications::registerNodeSrv > {
  static const char* value()
  {
    return "state_manager_communications/registerNodeSrv";
  }

  static const char* value(const ::state_manager_communications::registerNodeSrv&) { return value(); }
};


// service_traits::MD5Sum< ::state_manager_communications::registerNodeSrvRequest> should match 
// service_traits::MD5Sum< ::state_manager_communications::registerNodeSrv > 
template<>
struct MD5Sum< ::state_manager_communications::registerNodeSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_manager_communications::registerNodeSrv >::value();
  }
  static const char* value(const ::state_manager_communications::registerNodeSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_manager_communications::registerNodeSrvRequest> should match 
// service_traits::DataType< ::state_manager_communications::registerNodeSrv > 
template<>
struct DataType< ::state_manager_communications::registerNodeSrvRequest>
{
  static const char* value()
  {
    return DataType< ::state_manager_communications::registerNodeSrv >::value();
  }
  static const char* value(const ::state_manager_communications::registerNodeSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_manager_communications::registerNodeSrvResponse> should match 
// service_traits::MD5Sum< ::state_manager_communications::registerNodeSrv > 
template<>
struct MD5Sum< ::state_manager_communications::registerNodeSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_manager_communications::registerNodeSrv >::value();
  }
  static const char* value(const ::state_manager_communications::registerNodeSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_manager_communications::registerNodeSrvResponse> should match 
// service_traits::DataType< ::state_manager_communications::registerNodeSrv > 
template<>
struct DataType< ::state_manager_communications::registerNodeSrvResponse>
{
  static const char* value()
  {
    return DataType< ::state_manager_communications::registerNodeSrv >::value();
  }
  static const char* value(const ::state_manager_communications::registerNodeSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_MANAGER_COMMUNICATIONS_MESSAGE_REGISTERNODESRV_H
