/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mike/philosophers_experiments/philosophers/src/state_manager_communications/msg/robotModeMsg.msg
 *
 */


#ifndef STATE_MANAGER_COMMUNICATIONS_MESSAGE_ROBOTMODEMSG_H
#define STATE_MANAGER_COMMUNICATIONS_MESSAGE_ROBOTMODEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace state_manager_communications
{
template <class ContainerAllocator>
struct robotModeMsg_
{
  typedef robotModeMsg_<ContainerAllocator> Type;

  robotModeMsg_()
    : nodeName()
    , mode(0)
    , type(0)  {
    }
  robotModeMsg_(const ContainerAllocator& _alloc)
    : nodeName(_alloc)
    , mode(0)
    , type(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nodeName_type;
  _nodeName_type nodeName;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _type_type;
  _type_type type;


    enum { MODE_OFF = 0 };
     enum { MODE_NORMAL = 1 };
     enum { TYPE_TRANSITION = 0 };
     enum { TYPE_START = 1 };
     enum { TYPE_REQUEST = 3 };
     enum { TYPE_ACK = 4 };
 

  typedef boost::shared_ptr< ::state_manager_communications::robotModeMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_manager_communications::robotModeMsg_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct robotModeMsg_

typedef ::state_manager_communications::robotModeMsg_<std::allocator<void> > robotModeMsg;

typedef boost::shared_ptr< ::state_manager_communications::robotModeMsg > robotModeMsgPtr;
typedef boost::shared_ptr< ::state_manager_communications::robotModeMsg const> robotModeMsgConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_manager_communications::robotModeMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace state_manager_communications

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'state_manager_communications': ['/home/mike/philosophers_experiments/philosophers/src/state_manager_communications/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_manager_communications::robotModeMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_manager_communications::robotModeMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_manager_communications::robotModeMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f72c1608aab809dbbc4df281d3ec0dfa";
  }

  static const char* value(const ::state_manager_communications::robotModeMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf72c1608aab809dbULL;
  static const uint64_t static_value2 = 0xbc4df281d3ec0dfaULL;
};

template<class ContainerAllocator>
struct DataType< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_manager_communications/robotModeMsg";
  }

  static const char* value(const ::state_manager_communications::robotModeMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nodeName\n\
\n\
uint8 mode\n\
uint8 MODE_OFF = 0\n\
uint8 MODE_NORMAL = 1\n\
\n\
\n\
uint8 type\n\
uint8 TYPE_TRANSITION = 0\n\
uint8 TYPE_START = 1\n\
uint8 TYPE_REQUEST = 3\n\
uint8 TYPE_ACK = 4\n\
\n\
";
  }

  static const char* value(const ::state_manager_communications::robotModeMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeName);
      stream.next(m.mode);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robotModeMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_manager_communications::robotModeMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_manager_communications::robotModeMsg_<ContainerAllocator>& v)
  {
    s << indent << "nodeName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nodeName);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_MANAGER_COMMUNICATIONS_MESSAGE_ROBOTMODEMSG_H
