"""autogenerated by genpy from dining_philosopher_communications/hungerMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class hungerMsg(genpy.Message):
  _md5sum = "2ef8966f041358b93b05d3bf19cafa12"
  _type = "dining_philosopher_communications/hungerMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64 philosopherId

float64 hungerLevel

"""
  __slots__ = ['philosopherId','hungerLevel']
  _slot_types = ['uint64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       philosopherId,hungerLevel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(hungerMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.philosopherId is None:
        self.philosopherId = 0
      if self.hungerLevel is None:
        self.hungerLevel = 0.
    else:
      self.philosopherId = 0
      self.hungerLevel = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_Qd.pack(_x.philosopherId, _x.hungerLevel))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.philosopherId, _x.hungerLevel,) = _struct_Qd.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_Qd.pack(_x.philosopherId, _x.hungerLevel))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.philosopherId, _x.hungerLevel,) = _struct_Qd.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Qd = struct.Struct("<Qd")
