/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mike/svn/nasia/trunk/philosophers/src/dining_philosopher_communications/msg/hungerMsg.msg
 *
 */


#ifndef DINING_PHILOSOPHER_COMMUNICATIONS_MESSAGE_HUNGERMSG_H
#define DINING_PHILOSOPHER_COMMUNICATIONS_MESSAGE_HUNGERMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dining_philosopher_communications
{
template <class ContainerAllocator>
struct hungerMsg_
{
  typedef hungerMsg_<ContainerAllocator> Type;

  hungerMsg_()
    : hungerLevel(0.0)
    , faulty(0)  {
    }
  hungerMsg_(const ContainerAllocator& _alloc)
    : hungerLevel(0.0)
    , faulty(0)  {
    }



   typedef double _hungerLevel_type;
  _hungerLevel_type hungerLevel;

   typedef int16_t _faulty_type;
  _faulty_type faulty;




  typedef boost::shared_ptr< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct hungerMsg_

typedef ::dining_philosopher_communications::hungerMsg_<std::allocator<void> > hungerMsg;

typedef boost::shared_ptr< ::dining_philosopher_communications::hungerMsg > hungerMsgPtr;
typedef boost::shared_ptr< ::dining_philosopher_communications::hungerMsg const> hungerMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dining_philosopher_communications

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dining_philosopher_communications': ['/home/mike/svn/nasia/trunk/philosophers/src/dining_philosopher_communications/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40140d6023099e34d518ba49c1fc4b55";
  }

  static const char* value(const ::dining_philosopher_communications::hungerMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40140d6023099e34ULL;
  static const uint64_t static_value2 = 0xd518ba49c1fc4b55ULL;
};

template<class ContainerAllocator>
struct DataType< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dining_philosopher_communications/hungerMsg";
  }

  static const char* value(const ::dining_philosopher_communications::hungerMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float64 hungerLevel\n\
int16 faulty\n\
\n\
";
  }

  static const char* value(const ::dining_philosopher_communications::hungerMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hungerLevel);
      stream.next(m.faulty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct hungerMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dining_philosopher_communications::hungerMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dining_philosopher_communications::hungerMsg_<ContainerAllocator>& v)
  {
    s << indent << "hungerLevel: ";
    Printer<double>::stream(s, indent + "  ", v.hungerLevel);
    s << indent << "faulty: ";
    Printer<int16_t>::stream(s, indent + "  ", v.faulty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DINING_PHILOSOPHER_COMMUNICATIONS_MESSAGE_HUNGERMSG_H
