/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mike/philosophers_experiments/philosophers/src/watchdog_timer/srv/watchdogSrv.srv
 *
 */


#ifndef WATCHDOG_TIMER_MESSAGE_WATCHDOGSRV_H
#define WATCHDOG_TIMER_MESSAGE_WATCHDOGSRV_H

#include <ros/service_traits.h>


#include <watchdog_timer/watchdogSrvRequest.h>
#include <watchdog_timer/watchdogSrvResponse.h>


namespace watchdog_timer
{

struct watchdogSrv
{

typedef watchdogSrvRequest Request;
typedef watchdogSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct watchdogSrv
} // namespace watchdog_timer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::watchdog_timer::watchdogSrv > {
  static const char* value()
  {
    return "df769c8ebbf1228924a2ae49d71f0000";
  }

  static const char* value(const ::watchdog_timer::watchdogSrv&) { return value(); }
};

template<>
struct DataType< ::watchdog_timer::watchdogSrv > {
  static const char* value()
  {
    return "watchdog_timer/watchdogSrv";
  }

  static const char* value(const ::watchdog_timer::watchdogSrv&) { return value(); }
};


// service_traits::MD5Sum< ::watchdog_timer::watchdogSrvRequest> should match 
// service_traits::MD5Sum< ::watchdog_timer::watchdogSrv > 
template<>
struct MD5Sum< ::watchdog_timer::watchdogSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::watchdog_timer::watchdogSrv >::value();
  }
  static const char* value(const ::watchdog_timer::watchdogSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::watchdog_timer::watchdogSrvRequest> should match 
// service_traits::DataType< ::watchdog_timer::watchdogSrv > 
template<>
struct DataType< ::watchdog_timer::watchdogSrvRequest>
{
  static const char* value()
  {
    return DataType< ::watchdog_timer::watchdogSrv >::value();
  }
  static const char* value(const ::watchdog_timer::watchdogSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::watchdog_timer::watchdogSrvResponse> should match 
// service_traits::MD5Sum< ::watchdog_timer::watchdogSrv > 
template<>
struct MD5Sum< ::watchdog_timer::watchdogSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::watchdog_timer::watchdogSrv >::value();
  }
  static const char* value(const ::watchdog_timer::watchdogSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::watchdog_timer::watchdogSrvResponse> should match 
// service_traits::DataType< ::watchdog_timer::watchdogSrv > 
template<>
struct DataType< ::watchdog_timer::watchdogSrvResponse>
{
  static const char* value()
  {
    return DataType< ::watchdog_timer::watchdogSrv >::value();
  }
  static const char* value(const ::watchdog_timer::watchdogSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WATCHDOG_TIMER_MESSAGE_WATCHDOGSRV_H
