/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mike/philosophers_experiments/philosophers/src/watchdog_timer/srv/watchdogSrv.srv
 *
 */


#ifndef WATCHDOG_TIMER_MESSAGE_WATCHDOGSRVREQUEST_H
#define WATCHDOG_TIMER_MESSAGE_WATCHDOGSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace watchdog_timer
{
template <class ContainerAllocator>
struct watchdogSrvRequest_
{
  typedef watchdogSrvRequest_<ContainerAllocator> Type;

  watchdogSrvRequest_()
    : watchdogName()
    , type(0)
    , timeoutDuration()  {
    }
  watchdogSrvRequest_(const ContainerAllocator& _alloc)
    : watchdogName(_alloc)
    , type(0)
    , timeoutDuration()  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _watchdogName_type;
  _watchdogName_type watchdogName;

   typedef uint8_t _type_type;
  _type_type type;

   typedef ros::Duration _timeoutDuration_type;
  _timeoutDuration_type timeoutDuration;


    enum { TYPE_STOP = 0 };
     enum { TYPE_START = 1 };
 

  typedef boost::shared_ptr< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct watchdogSrvRequest_

typedef ::watchdog_timer::watchdogSrvRequest_<std::allocator<void> > watchdogSrvRequest;

typedef boost::shared_ptr< ::watchdog_timer::watchdogSrvRequest > watchdogSrvRequestPtr;
typedef boost::shared_ptr< ::watchdog_timer::watchdogSrvRequest const> watchdogSrvRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace watchdog_timer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'watchdog_timer': ['/home/mike/philosophers_experiments/philosophers/src/watchdog_timer/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df769c8ebbf1228924a2ae49d71f0000";
  }

  static const char* value(const ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf769c8ebbf12289ULL;
  static const uint64_t static_value2 = 0x24a2ae49d71f0000ULL;
};

template<class ContainerAllocator>
struct DataType< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "watchdog_timer/watchdogSrvRequest";
  }

  static const char* value(const ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string watchdogName\n\
uint8 type\n\
uint8 TYPE_STOP = 0\n\
uint8 TYPE_START = 1\n\
duration timeoutDuration\n\
\n\
\n\
";
  }

  static const char* value(const ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.watchdogName);
      stream.next(m.type);
      stream.next(m.timeoutDuration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct watchdogSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::watchdog_timer::watchdogSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "watchdogName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.watchdogName);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "timeoutDuration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.timeoutDuration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WATCHDOG_TIMER_MESSAGE_WATCHDOGSRVREQUEST_H
